name: Common CI/CD

on:
  push:
    branches:
      - "staging"
      - "release/*"
    paths:
      - "common/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./common
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2

      - name: Install Dependencies
        run: pnpm i

      - name: Run Tests
        run: pnpm test
